detekt.use.worker.api=true

org.gradle.caching=true
org.gradle.configuration-cache.problems=fail
org.gradle.configuration-cache=true
org.gradle.console=colored
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.vfs.watch=true
org.gradle.welcome=never
org.gradle.workers.max=4

kotlin.code.style=official
kotlin.stdlib.default.dependency=false

SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true
RELEASE_SIGNING_ENABLED=true

GROUP=dev.jonpoulton.detekt
VERSION_NAME=0.1.0

POM_ARTIFACT_ID=gradle-detekt-rules
POM_NAME=Gradle Detekt Rules
POM_DESCRIPTION=Detekt rules to be applied on Gradle scripts
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/jonapoul/gradle-detekt-rules
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/jonapoul/gradle-detekt-rules
POM_SCM_CONNECTION=scm:git:git://github.com/jonapoul/gradle-detekt-rules.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/jonapoul/gradle-detekt-rules.git
POM_DEVELOPER_ID=jonapoul
POM_DEVELOPER_NAME=Jon Poulton
POM_DEVELOPER_URL=https://github.com/jonapoul/
