name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CI: true
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2

      - name: Shellcheck
        run: shellcheck scripts/*.sh

      - name: Validate renovate config
        run: |
          npm install -g renovate
          renovate-config-validator

      - uses: dortort/betterleaks-action@cd0b905aa4befb8f42f8b1ab98150180c9e77515 # v0.1.0
        id: betterleaks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: ./config/betterleaks.toml
          fail-on-leak: 'true'

      - uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4
        if: always()
        with:
          sarif_file: ${{ steps.betterleaks.outputs.sarif-path }}
          category: betterleaks

      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          java-version-file: .java-version
          distribution: zulu

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
        with:
          add-job-summary: on-failure
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-encryption-key: ${{ env.GRADLE_ENCRYPTION_KEY }}

      - run: scripts/ktfmt.sh check --force

      - name: Check
        run: ./gradlew check --continue

      - name: Upload detekt SARIF
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: build/reports/detekt/merged.sarif
          category: detekt

      - name: Validate publication
        if: ${{ !cancelled() }}
        run: ./gradlew publishToMavenLocal -PRELEASE_SIGNING_ENABLED=false

      - uses: gmazzo/publish-report-annotations@d9c7375f4c587879eeedba56c6e35f1235219f9f # v1
        if: ${{ !cancelled() }}
